indexdomconnect = {name: "indexdomconnect"}

############################################################
indexdomconnect.initialize = () ->
    global.doctorLoginBlock = document.getElementById("doctor-login-block")
    global.patientLoginBlock = document.getElementById("patient-login-block")
    global.doctorloginview = document.getElementById("doctorloginview")
    global.doctorloginHeading = document.getElementById("doctorlogin-heading")
    global.doctormiscContinueButton = document.getElementById("doctormisc-continue-button")
    global.getLoginDataButton = document.getElementById("get-login-data-button")
    global.doctorloginForm = document.getElementById("doctorlogin-form")
    global.vpnInput = document.getElementById("vpn-input")
    global.usernameInput = document.getElementById("username-input")
    global.passwordInput = document.getElementById("password-input")
    global.saveLoginInput = document.getElementById("save-login-input")
    global.doctorloginSubmitButton = document.getElementById("doctorlogin-submit-button")
    global.compatibilityloginview = document.getElementById("compatibilityloginview")
    global.compatibilityloginHeading = document.getElementById("compatibilitylogin-heading")
    global.requestcodeformblock = document.getElementById("requestcodeformblock")
    global.noPinQuestion = document.getElementById("no-pin-question")
    global.requestCodeForm = document.getElementById("request-code-form")
    global.requestPhoneInput = document.getElementById("request-phone-input")
    global.requestCodeErrorFeedbackText = document.getElementById("request-code-error-feedback-text")
    global.requestCodeSubmitButton = document.getElementById("request-code-submit-button")
    global.compatibilityAuthcodeLoginForm = document.getElementById("compatibility-authcode-login-form")
    global.authcodeInput = document.getElementById("authcode-input")
    global.authcodeErrorFeedbackText = document.getElementById("authcode-error-feedback-text")
    global.authcodeSubmitButton = document.getElementById("authcode-submit-button")
    global.compatibilitySvnLoginForm = document.getElementById("compatibility-svn-login-form")
    global.svnPartInput = document.getElementById("svn-part-input")
    global.birthdayPartInput = document.getElementById("birthday-part-input")
    global.pinInput = document.getElementById("pin-input")
    global.svnErrorFeedbackText = document.getElementById("svn-error-feedback-text")
    global.svnSubmitButton = document.getElementById("svn-submit-button")
    global.svnLoginError404 = document.getElementById("svn-login-error404")
    global.svnLoginError401 = document.getElementById("svn-login-error401")
    global.nosvnLoginError = document.getElementById("nosvn-login-error")
    global.pinRenewError = document.getElementById("pin-renew-error")
    global.requestCodeSuccess = document.getElementById("request-code-success")
    return
    
module.exports = indexdomconnect